### ISSUE TITLE
Plugin overriding user colors

### ISSUE THREAD

**Issue by iamrecursion** [tomaz1502/lean-syntax-highlight#1]
I have my own colors set up, but when this is enabled it changes the highlighting for my frontmatter, math blocks, and so on.

**Comment by tomaz1502** [comment]
Thanks - I removed the `styles.scss` file and tested it locally, it seems that the plugin does not overwrite the colors anymore.

**Comment by iamrecursion** [comment]
It's still occurring for me. In particular, with the plugin enabled my frontmatter uses a totally different set of colors. 

With the plugin enabled:

<img width="240" alt="image" src="https://github.com/tomaz1502/lean-syntax-highlight/assets/5780639/96480fd4-367d-42d9-9c62-029dfcc016c9">

Without the plugin enabled:

<img width="219" alt="image" src="https://github.com/tomaz1502/lean-syntax-highlight/assets/5780639/052809f4-42dc-4e8a-a5ec-988fbaafc3a9">

**Comment by tomaz1502** [comment]
That's really odd, considering that there isn't anymore CSS in the plugin. Could you provide steps to reproduce, please? I tested the math blocks, and they indeed were not having their colors overwritten by the plugin on my machine.

**Comment by iamrecursion** [comment]
It looks like this was my mistake! Updating the plugin did not remove the CSS, so I had to that manually. Now there is no issue.
